# Generated by Django 2.0.5 on 2018-05-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
            ],
            options={
                'verbose_name': '분류',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='media/', verbose_name='이미지')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='분류')),
            ],
            options={
                'verbose_name': '글',
                'ordering': ['created'],
            },
        ),
    ]
